// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOXFKJz4UvhmzfCl25ic5wQ41x53mTec',
    appId: '1:749190821655:web:a55c5acb1466f8592aa952',
    messagingSenderId: '749190821655',
    projectId: 'application-55834',
    authDomain: 'application-55834.firebaseapp.com',
    storageBucket: 'application-55834.appspot.com',
    measurementId: 'G-GRBNX1PGXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6t0MxUprV-mtEKiLYnayn-ezHuL4vbE',
    appId: '1:749190821655:android:9a89e11e2c26bab42aa952',
    messagingSenderId: '749190821655',
    projectId: 'application-55834',
    storageBucket: 'application-55834.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0GCL6yHGnZ9eauk87RFcnPwe2f3MtpQ',
    appId: '1:749190821655:ios:510dc0465b9b70642aa952',
    messagingSenderId: '749190821655',
    projectId: 'application-55834',
    storageBucket: 'application-55834.appspot.com',
    iosBundleId: 'com.example.application',
  );

}